### ISSUE TITLE
docker / repo2docker rebuilding layers although no changes were made

### ISSUE THREAD

**Issue by bveliqi** [bveliqi/adversarial-vision-challenge#17]

**Comment by spMohanty** [comment]
@bveliqi : If this is in reference to the message on the gitter channel, then I think the participant mentioned that it was rebuilding when the participant was making minor code changes. Which is expected behaviour. 
But that should be dealt with by passing `--no-build` after https://github.com/bethgelab/adversarial-vision-challenge/pull/19 is merged.

**Comment by bveliqi** [comment]
Duplicate of  #18
