### ISSUE TITLE
Validate adversarials in `store_adversarial`

### ISSUE THREAD

**Issue by spMohanty** [bveliqi/adversarial-vision-challenge#5]
https://github.com/bethgelab/adversarial-vision-challenge/blob/master/adversarial_vision_challenge/utils.py#L48

This will ensure that if the attacker is storing adversarial images in a wrong format (say with pixel values `[0, 255]` instead of `[0, 1]` ) then we throw an error as soon as we can, instead of letting the evaluator pick it up at the end of the attack.

**Comment by jonasrauber** [comment]
@spMohanty I agree; I mentioned this before as well; but I would actually save them in the same format as they are passed to the attack and expected to be passed from the attack to the model: in the range of [0, 255] (in fact, for transmission we clip and convert to uint8 to avoid leaking information to the model that makes it easy to differentiate between images and adversarials). I think we should therefore also save the adversarials in that format, i.e. clip to [0, 255], then convert to uint8, then save. Do you agree, @wielandbrendel ? Of course, in the evaluator we need to make sure to check that the saved adversarials have uint8 dtype because we cannot trust the attack, and if they are not, an attack can simply be disqualified.
@bveliqi can you implement this, following what we do in the `predict` method (https://github.com/bethgelab/adversarial-vision-challenge/blob/master/adversarial_vision_challenge/client.py#L139), i.e. converting float32 to uint8 if necessary. While you are at it, it would be great to check and document that the format returned by `read_images` is float32 with values in [0, 255] (I think that's what we agreed on, right?).

**Comment by bveliqi** [comment]
pls check https://github.com/bethgelab/adversarial-vision-challenge/pull/6

**Comment by jonasrauber** [comment]
This is fixed with the updated avc lib and the updated evaluation code.
